language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
  - ./gradlew clean
script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)