spring:
    h2:
        console:
            enabled: true
            path: "/h2-console"
security:
    jwt:
        token:
            secret-key: v9y$B&E)H@McQfTjWnZr4u7w!z%C*F-J
            expire-length: 36000000
            token-prefix: Bearer 
            header: Authorization
server:
    port: 9000