spring:
    h2:
        console:
            enabled: true
            path: "/h2-console" 
security:
    jwt:
        token:
            secret-key: v9y$B&E)H@McQfTjWnZr4u7w!z%C*F-J
            expire-length: 300000
server:
    port: 8080