name: Spring Boot CI

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
  test:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew test
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Heroku
      uses: actions/heroku@master
      with:
        secrets: 2e9c4210-3350-47c7-ba74-eda8472323d8
