name: Spring Boot CI

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew test
  deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secret.HEROKU_APP }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Remote Set up
      run: heroku git:remote -a $(basename $GITHUB_REPOSITORY)
    - name: Push
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP.git origin/master:master
